config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resource :profile, only: [:show, :update]
    resources :users
    resources :work_spaces
    resources :questions
    resources :answers
  end

  namespace :leader do
    resource :profile, only: [:show, :update]
    resources :work_spaces
    resources :questions
    resources :answers
  end

  root to: "home#index"
  devise_for :users

  post 'slack/button'
  get '/successful' , to: "home#successful"
  get '/check_auth' , to: "home#check_auth"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_bot.rb
class ChatBot
  def self.send_message
    questions = Question.where(active: true)
    questions.each do |question|
      client = Slack::Web::Client.new
      client.token = question.work_space.token
      users = client.users_list.members.select do |member|
        member.profile.email.present? && member.is_bot == false && member.deleted == false
      end
      choices = question.choice

      if question.type_question == true
        content = {
          channel: question.id_channel_slack,
          text: question.content,
          as_user:  "true",
          attachments: [{
            text: "Bỏ phiếu nha",
            color: "#3AA3E3",
            attachment_type: "default",
            callback_id: "select_status",
            actions: choices.map do |choice|
              {
                name: choice.name,
                text: choice.name,
                type: "button",
                value: choice.id
              }
            end
          }]
        }
        client.chat_postMessage(content)
      else
        users.each do |user|
          content = {
            channel: user.id,
            text: question.content,
            as_user:  "true",
            attachments: [{
              text: "Bỏ phiếu nha",
              color: "#3AA3E3",
              attachment_type: "default",
              callback_id: "select_status",
              actions: choices.map do |choice|
                {
                  name: choice.name,
                  text: choice.name,
                  type: "button",
                  value: choice.id
                }
              end
            }]
          }
          client.chat_postMessage(content)
        end
      end
    end
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  has_many :answer
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :work_space
  has_many :choice, dependent: :destroy
  has_many :answer
end

app/models/user.rb
class User < ApplicationRecord
  has_many :work_space, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def is_admin?
    return true if self.roles == 0
    false
  end
end

app/models/work_space.rb
class WorkSpace < ApplicationRecord
  belongs_to :user
  has_many :question, dependent: :destroy
end

app/controllers/admin/admin_base_controller.rb
class Admin::AdminBaseController < BaseController
  before_action :authenticate_user!
  before_action :is_admin_page?

  def is_admin_page?
    return redirect_to leader_work_spaces_path unless current_user.is_admin?
  end
end

app/controllers/admin/work_spaces_controller.rb
class Admin::WorkSpacesController < Admin::AdminBaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  layout :layout_by_resource

  def layout_by_resource
    return 'application' unless devise_controller?
    'devise'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def successful; end

  def check_auth
    if params['code'].present?
      data = {
        :client_id => ENV['SLACK_CLIENT_ID'],
        :client_secret => ENV['SLACK_CLIENT_SECRET'],
        :code => params['code'],
      }

      url = "https://slack.com/api/oauth.access"

      response = Faraday.post(url) do |req|
        req.headers['Content-Type'] = 'application/x-www-form-urlencoded'
        req.body = URI.encode_www_form(data)
      end

      information = JSON.parse(response&.body || "{}")

      work_space_check = WorkSpace.find_by(id_work_space_slack: information['team_id'] )

      if work_space_check.present?
        redirect_to root_path
      else
        work_space = WorkSpace.new
        work_space.name = information['team_name']
        work_space.token = information['bot']['bot_access_token']
        work_space.id_work_space_slack = information['team_id']
        work_space.user_id = current_user.id
        if work_space.save
          redirect_to successful_path
        end
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/leader/leader_base_controller.rb
class Leader::LeaderBaseController < BaseController
  before_action :authenticate_user!
  before_action :is_admin_page?

  def is_admin_page?
    return redirect_to admin_work_spaces_path if current_user.is_admin?
  end
end

app/controllers/leader/work_spaces_controller.rb
class Leader::WorkSpacesController < Leader::LeaderBaseController
  def index
  end
end

app/controllers/slack_controller.rb
require 'json'
require 'uri'
require 'net/http'

class SlackController < ApplicationController
  skip_before_action :verify_authenticity_token
  # before_action :check_verification_token

  def self.send_response(response_url, msg)
    url = URI.parse(response_url)
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(url)
    request['content-type'] = 'application/json'
    request.body = JSON[msg]
    response = http.request(request)
  end

  def button
    request_data = JSON.parse(params.dig('payload'))
    work_space = WorkSpace.find_by(id_work_space_slack: request_data['team']['id'])
    question = work_space.question.find_by(content: request_data['original_message']['text'])
    client = Slack::Web::Client.new
    client.token = question.work_space.token

    users = client.users_list.members.select do |member|
      member.profile.email.present? && member.is_bot == false && member.deleted == false
    end

    members = users.map do |user|
      {
        name: user.profile.real_name,
        email: user.profile.email
      }
    end

    answer = Answer.new
    answer.question_id = question.id
    answer.choice_id = question.choice.find_by(id: request_data['actions'].first['value']).id
    answer.member_name = members.select{|e| e[:name] == request_data['user']['name'] }.first[:name]
    answer.member_email = members.select{|e| e[:name] == request_data['user']['name'] }.first[:email]

    url = request_data['response_url']
    case request_data['callback_id']
    when 'select_status'
      msg = request_data['original_message']
      msg['text'] = ':heavy_check_mark: Cảm ơn bạn đã bỏ phiếu, chúc bạn làm việc vui vẻ :star-struck:'
      msg['attachments'] = []

      if answer.save
        SlackController.send_response(url, msg)
      end
    end
  end

  private

  def check_verification_token
    unless params.dig('payload').present? && JSON.parse(params.dig('payload'))['token'] == ENV['SLACK_VERIFICATION_TOKEN']
      render json: { errors: ['user not authorized']}, status: :forbidden and return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_class_active(path)
    current_route = Rails.application.routes.recognize_path(path)
    "active" if current_page?(path) or params[:controller] == current_route[:controller]
  end

  def display_submenu(path)
    current_route = Rails.application.routes.recognize_path(path)
    "in" if current_page?(path) or params[:controller] == current_route[:controller]
  end

  def add_active_sub_menu_action_new(path)
    current_route = Rails.application.routes.recognize_path(path)
    "active" if current_page?(path) or (params[:controller] == current_route[:controller] and controller.action_name == 'new')
  end

  def add_active_sub_menu(path)
    current_route = Rails.application.routes.recognize_path(path)
    "active" if current_page?(path) or (params[:controller] == current_route[:controller] and controller.action_name != 'new')
  end
end

app/views/admin/work_spaces/index.html.erb
index.html.rb

app/views/home/_header.html.erb
<div class="page-title-area">
  <div class="row align-items-center">

    <% if current_user.nil? %>
      <div class="col-sm-12 clearfix">
        <div class="pull-right">
          <button class="btn btn-primary btn-sign-in" type="button">
            <%= link_to "Sign In", new_user_session_path %>
          </button>
        </div>
        <div class="pull-right">
          <button class="btn btn-danger btn-sign-up" type="button" >
            <%= link_to "Sign Up", new_user_registration_path %>
          </button>
        </div>
      </div>
    <% else %>
      <div class="col-sm-12 clearfix">
        <div class="pull-right">
          <div class="dropdown">
            <button class="btn btn-primary btn-profile" type="button" data-toggle="dropdown">
              <i class="fa fa-user"></i>
              <span class="caret"></span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <%#= link_to "Thông tin", admin_profile_path, class: "dropdown-item" %></br>
              <%= link_to "Đăng xuất", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </div>
        <div class="pull-right">
          <% if current_user.is_admin? %>
            <button class="btn btn-primary btn-profile" type="button">
              <%= link_to "Dasboard", admin_work_spaces_path %>
            </button>
          <% else %>
            <% if current_user.work_space.count >= 2 %>
              <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Dasboard</button>

              <div id="myModal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <div class="modal-body">
                      <p>Some text in the modal.</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            <% else %>
              <button class="btn btn-primary btn-profile" type="button">
                <%= link_to "Dasboard", leader_work_spaces_path %>
              </button>
            <%end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <a href="https://slack.com/oauth/authorize?scope=bot&client_id=646759876034.651830099937"><img alt=""Add to Slack"" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" /></a>
<% end %>

app/views/home/successful.html.erb
<h1>Succesful</h1>

app/views/layouts/_flash_message.html.erb
<% if flash[:success] %>
  <div class="notification is-primary global-notification">
    <p class="alert alert-success"><%= flash[:success] %></p>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="notification is-danger global-notification">
    <p class="alert alert-danger"><%= flash[:error] %></p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="page-title-area">
  <div class="row align-items-center">
    <div class="col-sm-12 clearfix">
      <div class="pull-right">
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle btn-profile" type="button" data-toggle="dropdown">
            <i class="fa fa-user"></i>
            <span class="caret"></span>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <%#= link_to "Thông tin", admin_profile_path, class: "dropdown-item" %></br>
            <%= link_to "Đăng xuất", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-menu">
  <div class="sidebar-header">
    <div class="logo">
      <%= image_tag("images/slack.png", class: "logo-slack") %></br>
      <a href="/"><h2><%= "SlackBot" %></h2></a>
    </div>
    <div class="main-menu">
      <div class="menu-inner">
        <nav>
          <ul class="metismenu" id="menu">
            <li class="<%= add_class_active('admin/work_spaces') %>">
              <a href="javascript:void(0)" data-toggle="collapse" data-target="#sidebar-work_spaces"><%= t('label.sidebar.work_spaces') %></a>
              <ul class="collapse <%= display_submenu('admin/work_spaces') %> " id="sidebar-work_spaces">
                <li class="<%= add_active_sub_menu('admin/work_spaces') %>">
                  <%#= link_to "Index", admin_answesheets_path %>
                </li>
              </ul>
            </li>
          </ul>
          <!-- <ul class="metismenu" id="menu">
            <li class="<%#= add_class_active('admin/questions') %>">
              <a href="javascript:void(0)" data-toggle="collapse" data-target="#sidebar-questions"><%#= t('label.sidebar.questions') %></a>
              <ul class="collapse <%#= display_submenu('admin/questions') %> " id="sidebar-questions">
                <li class="<%#= add_active_sub_menu('admin/questions') %>">
                  <%#= link_to "Index", admin_questions_path %>
                </li>
                <li class="<%#= add_active_sub_menu_action_new('admin/questions') %>">
                  <%#= link_to "Add Questions", new_admin_question_path %>
                </li>
              </ul>
            </li>
          </ul>
          <ul class="metismenu" id="menu">
            <li class="<%#= add_class_active('admin/users') %>">
              <a href="javascript:void(0)" data-toggle="collapse" data-target="#sidebar-users"><%#= t('label.sidebar.users') %></a>
              <ul class="collapse <%#= display_submenu('admin/users') %> " id="sidebar-users">
                <li class="<%#= add_active_sub_menu('admin/users') %>">
                  <%#= link_to "Index", admin_users_path %>
                </li>
              </ul>
            </li>
          </ul> -->
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_will_paginate.html.erb
<div class="pagination navbar ">
  <%= will_paginate data, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackRubyBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page-container">
      <%= render  "layouts/sidebar" %>
      <%= render  "layouts/header" %>
      <div class="main-content-inner">
        <div class="row">
          <div class="col-12 mt-5">
            <div class="card">
              <div class="card-body">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackRubyBot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackRubyBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "home/header" %>
    <div class="main-content-inner">
      <div class="row">
        <div class="col-12 mt-5">
          <div class="card">
            <div class="card-body">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/leader/work_spaces/index.html.erb
index.html.erb